
{
# 公众号配置
# 公众号appId
"app_id": "wxcc232638bcf0aa43",
# 公众号appSecret
"app_secret":4499af20128489c6c910a1db7603b582 "",
# 模板消息id
"template_id":MWWxSd9N2Tp3sFV9PPrp1HUCvoG6TUVkG4fx6XFqUt8 "",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["12b8d19ac146ea9287123bebfa7028ab"],

# 信息配置
# 和风天气apikey
"weather_key": ed249670139344f8920b466ee82fe859"",
# 天行数据apikey
"tian_api": 12b8d19ac146ea9287123bebfa7028ab" ",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦(国外城市可能获取不到pm2.5，空气质量，今日建议等数据)
"region": "新乡市",
# 生日1
"birthday1": {"name": "小李", "birthday": "2000-09-16"},
# 生日2
"birthday2": {"name": "小李", "birthday": "r2000-09-16"},
# 在一起的日子，格式同上
"love_date": "2022-09-01",
# 金句中文，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}
